//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorCv.Services {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InterfaceConstants {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InterfaceConstants() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BlazorCv.Services.InterfaceConstants", typeof(InterfaceConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        internal static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        internal static string studies {
            get {
                return ResourceManager.GetString("studies", resourceCulture);
            }
        }
        
        internal static string experience {
            get {
                return ResourceManager.GetString("experience", resourceCulture);
            }
        }
        
        internal static string skills {
            get {
                return ResourceManager.GetString("skills", resourceCulture);
            }
        }
        
        internal static string programmingLanguages {
            get {
                return ResourceManager.GetString("programmingLanguages", resourceCulture);
            }
        }
        
        internal static string programmingTools {
            get {
                return ResourceManager.GetString("programmingTools", resourceCulture);
            }
        }
        
        internal static string dataAccess {
            get {
                return ResourceManager.GetString("dataAccess", resourceCulture);
            }
        }
        
        internal static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        internal static string noData {
            get {
                return ResourceManager.GetString("noData", resourceCulture);
            }
        }
    }
}
